services:
  - type: web
    name: youtube-viewer-bot
    env: docker
    plan: standard
    buildCommand: docker build -t youtube-viewer-bot .
    startCommand: docker run youtube-viewer-bot
    envVars:
      - key: NUM_BOTS
        value: 100
      - key: VIEWS_PER_BOT
        value: 5
    autoDeploy: true
    disk:
      name: youtube-viewer-data
      mountPath: /app/data
      sizeGB: 1 