name: Keep Render App Awake

on:
  schedule:
    - cron: "*/4 * * * *"  # Runs every 4 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render app
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://navieviews.onrender.com
